# Generated by Django 4.2.2 on 2023-06-17 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("static_pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticPageTrans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locale", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("page_title", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("sub_title", models.CharField(blank=True, max_length=255, null=True)),
                ("btn_title", models.CharField(blank=True, max_length=255, null=True)),
                ("btn_link", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "static_page_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="static_page_trans",
                        to="static_pages.staticpage",
                    ),
                ),
            ],
        ),
    ]
