# Generated by Django 4.2.2 on 2023-06-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_staticpagetrans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticpagetrans',
            old_name='static_page_id',
            new_name='static_page',
        ),
    ]
