# Generated by Django 4.2.2 on 2023-07-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("static_pages", "0003_rename_static_page_id_staticpagetrans_static_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticpage",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
        migrations.AlterField(
            model_name="staticpagetrans",
            name="locale",
            field=models.CharField(choices=[("en", "en"), ("ar", "ar")], max_length=50),
        ),
    ]
